
COMPILER := "riscv64-unknown-linux-gnu-gcc"

compile: 
    {{COMPILER}} -e _start -static -nostdlib -fno-builtin -fno-stack-protector -fdata-sections -ffunction-sections -march=rv64gc -I$OPENPERF_HOME/src/common/klib/include -I$OPENPERF_HOME/src/common/am/include -o build/dry dry.c `find $OPENPERF_HOME/src/common/am -name '*.c'` `find $OPENPERF_HOME/src/common/klib -name '*.c'` `find $OPENPERF_HOME/src/common/am -name '*.S'` -T$OPENPERF_HOME/src/common/am/src/linker.ld
