binary: openperf-nemu/build/riscv32-nemu-interpreter
max_workers: 16
tests:
  nemu-ref:
    timeout: 50
    format: "-b build/images/{0}-ref.bin"
    parameters:
        0: [ "mcf", "x264", "tcc", "stream", "linpack", "gemm", "whetstone" ]
