NAME = cpuemu

# SRCS = test/top.cc resource.S test/mm.cc
# SRCS = train/emu.cc train/lshrdi3.c resource.S bench.cc

SRCS = main.cc resource.S test/top.cc test/mm.cc train/emu.cc

CXXFLAGS += -Wno-c++20-compat

include $(AM_HOME)/Makefile
